version: '3.8'

services:
  backend:
    build: ./api
    container_name: backend
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

